// Generated by tools/content-cli/src/sync-medication-identity-index.ts.
// Do not hand-edit; identity files remain the canonical per-medication owners.

import identity001Json from '../../../content/catalogs/medications/identities/acamprosate.identity.json';
import identity002Json from '../../../content/catalogs/medications/identities/alprazolam.identity.json';
import identity003Json from '../../../content/catalogs/medications/identities/amantadine.identity.json';
import identity004Json from '../../../content/catalogs/medications/identities/amitriptyline.identity.json';
import identity005Json from '../../../content/catalogs/medications/identities/amoxapine.identity.json';
import identity006Json from '../../../content/catalogs/medications/identities/amphetamine.identity.json';
import identity007Json from '../../../content/catalogs/medications/identities/aripiprazole.identity.json';
import identity008Json from '../../../content/catalogs/medications/identities/armodafinil.identity.json';
import identity009Json from '../../../content/catalogs/medications/identities/asenapine.identity.json';
import identity010Json from '../../../content/catalogs/medications/identities/atomoxetine.identity.json';
import identity011Json from '../../../content/catalogs/medications/identities/benztropine.identity.json';
import identity012Json from '../../../content/catalogs/medications/identities/brexpiprazole.identity.json';
import identity013Json from '../../../content/catalogs/medications/identities/buprenorphine.identity.json';
import identity014Json from '../../../content/catalogs/medications/identities/bupropion.identity.json';
import identity015Json from '../../../content/catalogs/medications/identities/buspirone.identity.json';
import identity016Json from '../../../content/catalogs/medications/identities/carbamazepine.identity.json';
import identity017Json from '../../../content/catalogs/medications/identities/cariprazine.identity.json';
import identity018Json from '../../../content/catalogs/medications/identities/chlordiazepoxide.identity.json';
import identity019Json from '../../../content/catalogs/medications/identities/chlorpromazine.identity.json';
import identity020Json from '../../../content/catalogs/medications/identities/citalopram.identity.json';
import identity021Json from '../../../content/catalogs/medications/identities/clomipramine.identity.json';
import identity022Json from '../../../content/catalogs/medications/identities/clonazepam.identity.json';
import identity023Json from '../../../content/catalogs/medications/identities/clonidine.identity.json';
import identity024Json from '../../../content/catalogs/medications/identities/clozapine.identity.json';
import identity025Json from '../../../content/catalogs/medications/identities/daridorexant.identity.json';
import identity026Json from '../../../content/catalogs/medications/identities/desipramine.identity.json';
import identity027Json from '../../../content/catalogs/medications/identities/desvenlafaxine.identity.json';
import identity028Json from '../../../content/catalogs/medications/identities/deutetrabenazine.identity.json';
import identity029Json from '../../../content/catalogs/medications/identities/dexmedetomidine.identity.json';
import identity030Json from '../../../content/catalogs/medications/identities/dexmethylphenidate.identity.json';
import identity031Json from '../../../content/catalogs/medications/identities/dextroamphetamine.identity.json';
import identity032Json from '../../../content/catalogs/medications/identities/diazepam.identity.json';
import identity033Json from '../../../content/catalogs/medications/identities/diphenhydramine.identity.json';
import identity034Json from '../../../content/catalogs/medications/identities/disulfiram.identity.json';
import identity035Json from '../../../content/catalogs/medications/identities/donepezil.identity.json';
import identity036Json from '../../../content/catalogs/medications/identities/doxazosin.identity.json';
import identity037Json from '../../../content/catalogs/medications/identities/doxepin.identity.json';
import identity038Json from '../../../content/catalogs/medications/identities/doxylamine.identity.json';
import identity039Json from '../../../content/catalogs/medications/identities/duloxetine.identity.json';
import identity040Json from '../../../content/catalogs/medications/identities/escitalopram.identity.json';
import identity041Json from '../../../content/catalogs/medications/identities/esketamine.identity.json';
import identity042Json from '../../../content/catalogs/medications/identities/eszopiclone.identity.json';
import identity043Json from '../../../content/catalogs/medications/identities/fluoxetine.identity.json';
import identity044Json from '../../../content/catalogs/medications/identities/fluphenazine.identity.json';
import identity045Json from '../../../content/catalogs/medications/identities/fluvoxamine.identity.json';
import identity046Json from '../../../content/catalogs/medications/identities/gabapentin.identity.json';
import identity047Json from '../../../content/catalogs/medications/identities/galantamine.identity.json';
import identity048Json from '../../../content/catalogs/medications/identities/gepirone.identity.json';
import identity049Json from '../../../content/catalogs/medications/identities/guanfacine.identity.json';
import identity050Json from '../../../content/catalogs/medications/identities/haloperidol.identity.json';
import identity051Json from '../../../content/catalogs/medications/identities/hydroxyzine.identity.json';
import identity052Json from '../../../content/catalogs/medications/identities/iloperidone.identity.json';
import identity053Json from '../../../content/catalogs/medications/identities/imipramine.identity.json';
import identity054Json from '../../../content/catalogs/medications/identities/isocarboxazid.identity.json';
import identity055Json from '../../../content/catalogs/medications/identities/ketamine.identity.json';
import identity056Json from '../../../content/catalogs/medications/identities/lamotrigine.identity.json';
import identity057Json from '../../../content/catalogs/medications/identities/lemborexant.identity.json';
import identity058Json from '../../../content/catalogs/medications/identities/levomilnacipran.identity.json';
import identity059Json from '../../../content/catalogs/medications/identities/liothyronine.identity.json';
import identity060Json from '../../../content/catalogs/medications/identities/lisdexamfetamine.identity.json';
import identity061Json from '../../../content/catalogs/medications/identities/lithium.identity.json';
import identity062Json from '../../../content/catalogs/medications/identities/lofexidine.identity.json';
import identity063Json from '../../../content/catalogs/medications/identities/lorazepam.identity.json';
import identity064Json from '../../../content/catalogs/medications/identities/loxapine.identity.json';
import identity065Json from '../../../content/catalogs/medications/identities/lumateperone.identity.json';
import identity066Json from '../../../content/catalogs/medications/identities/lurasidone.identity.json';
import identity067Json from '../../../content/catalogs/medications/identities/maprotiline.identity.json';
import identity068Json from '../../../content/catalogs/medications/identities/melatonin.identity.json';
import identity069Json from '../../../content/catalogs/medications/identities/memantine.identity.json';
import identity070Json from '../../../content/catalogs/medications/identities/metformin.identity.json';
import identity071Json from '../../../content/catalogs/medications/identities/methadone.identity.json';
import identity072Json from '../../../content/catalogs/medications/identities/methylphenidate.identity.json';
import identity073Json from '../../../content/catalogs/medications/identities/midazolam.identity.json';
import identity074Json from '../../../content/catalogs/medications/identities/mirtazapine.identity.json';
import identity075Json from '../../../content/catalogs/medications/identities/modafinil.identity.json';
import identity076Json from '../../../content/catalogs/medications/identities/molindone.identity.json';
import identity077Json from '../../../content/catalogs/medications/identities/naloxone.identity.json';
import identity078Json from '../../../content/catalogs/medications/identities/naltrexone.identity.json';
import identity079Json from '../../../content/catalogs/medications/identities/nefazodone.identity.json';
import identity080Json from '../../../content/catalogs/medications/identities/nicotine.identity.json';
import identity081Json from '../../../content/catalogs/medications/identities/nortriptyline.identity.json';
import identity082Json from '../../../content/catalogs/medications/identities/olanzapine.identity.json';
import identity083Json from '../../../content/catalogs/medications/identities/omega-3-fatty-acids.identity.json';
import identity084Json from '../../../content/catalogs/medications/identities/oxazepam.identity.json';
import identity085Json from '../../../content/catalogs/medications/identities/oxcarbazepine.identity.json';
import identity086Json from '../../../content/catalogs/medications/identities/paliperidone.identity.json';
import identity087Json from '../../../content/catalogs/medications/identities/paroxetine.identity.json';
import identity088Json from '../../../content/catalogs/medications/identities/perphenazine.identity.json';
import identity089Json from '../../../content/catalogs/medications/identities/phenelzine.identity.json';
import identity090Json from '../../../content/catalogs/medications/identities/phenobarbital.identity.json';
import identity091Json from '../../../content/catalogs/medications/identities/pimavanserin.identity.json';
import identity092Json from '../../../content/catalogs/medications/identities/pimozide.identity.json';
import identity093Json from '../../../content/catalogs/medications/identities/pitolisant.identity.json';
import identity094Json from '../../../content/catalogs/medications/identities/prazosin.identity.json';
import identity095Json from '../../../content/catalogs/medications/identities/pregabalin.identity.json';
import identity096Json from '../../../content/catalogs/medications/identities/propranolol.identity.json';
import identity097Json from '../../../content/catalogs/medications/identities/protriptyline.identity.json';
import identity098Json from '../../../content/catalogs/medications/identities/pyridoxine.identity.json';
import identity099Json from '../../../content/catalogs/medications/identities/quetiapine.identity.json';
import identity100Json from '../../../content/catalogs/medications/identities/ramelteon.identity.json';
import identity101Json from '../../../content/catalogs/medications/identities/risperidone.identity.json';
import identity102Json from '../../../content/catalogs/medications/identities/rivastigmine.identity.json';
import identity103Json from '../../../content/catalogs/medications/identities/selegiline.identity.json';
import identity104Json from '../../../content/catalogs/medications/identities/sertraline.identity.json';
import identity105Json from '../../../content/catalogs/medications/identities/solriamfetol.identity.json';
import identity106Json from '../../../content/catalogs/medications/identities/suvorexant.identity.json';
import identity107Json from '../../../content/catalogs/medications/identities/temazepam.identity.json';
import identity108Json from '../../../content/catalogs/medications/identities/thiothixene.identity.json';
import identity109Json from '../../../content/catalogs/medications/identities/topiramate.identity.json';
import identity110Json from '../../../content/catalogs/medications/identities/tranylcypromine.identity.json';
import identity111Json from '../../../content/catalogs/medications/identities/trazodone.identity.json';
import identity112Json from '../../../content/catalogs/medications/identities/triazolam.identity.json';
import identity113Json from '../../../content/catalogs/medications/identities/trifluoperazine.identity.json';
import identity114Json from '../../../content/catalogs/medications/identities/trimipramine.identity.json';
import identity115Json from '../../../content/catalogs/medications/identities/valbenazine.identity.json';
import identity116Json from '../../../content/catalogs/medications/identities/valproate.identity.json';
import identity117Json from '../../../content/catalogs/medications/identities/varenicline.identity.json';
import identity118Json from '../../../content/catalogs/medications/identities/venlafaxine.identity.json';
import identity119Json from '../../../content/catalogs/medications/identities/vilazodone.identity.json';
import identity120Json from '../../../content/catalogs/medications/identities/viloxazine.identity.json';
import identity121Json from '../../../content/catalogs/medications/identities/vortioxetine.identity.json';
import identity122Json from '../../../content/catalogs/medications/identities/zaleplon.identity.json';
import identity123Json from '../../../content/catalogs/medications/identities/ziprasidone.identity.json';
import identity124Json from '../../../content/catalogs/medications/identities/zolpidem.identity.json';
import identity125Json from '../../../content/catalogs/medications/identities/zuranolone.identity.json';

export const rawMedicationIdentityJson = [
  identity001Json,
  identity002Json,
  identity003Json,
  identity004Json,
  identity005Json,
  identity006Json,
  identity007Json,
  identity008Json,
  identity009Json,
  identity010Json,
  identity011Json,
  identity012Json,
  identity013Json,
  identity014Json,
  identity015Json,
  identity016Json,
  identity017Json,
  identity018Json,
  identity019Json,
  identity020Json,
  identity021Json,
  identity022Json,
  identity023Json,
  identity024Json,
  identity025Json,
  identity026Json,
  identity027Json,
  identity028Json,
  identity029Json,
  identity030Json,
  identity031Json,
  identity032Json,
  identity033Json,
  identity034Json,
  identity035Json,
  identity036Json,
  identity037Json,
  identity038Json,
  identity039Json,
  identity040Json,
  identity041Json,
  identity042Json,
  identity043Json,
  identity044Json,
  identity045Json,
  identity046Json,
  identity047Json,
  identity048Json,
  identity049Json,
  identity050Json,
  identity051Json,
  identity052Json,
  identity053Json,
  identity054Json,
  identity055Json,
  identity056Json,
  identity057Json,
  identity058Json,
  identity059Json,
  identity060Json,
  identity061Json,
  identity062Json,
  identity063Json,
  identity064Json,
  identity065Json,
  identity066Json,
  identity067Json,
  identity068Json,
  identity069Json,
  identity070Json,
  identity071Json,
  identity072Json,
  identity073Json,
  identity074Json,
  identity075Json,
  identity076Json,
  identity077Json,
  identity078Json,
  identity079Json,
  identity080Json,
  identity081Json,
  identity082Json,
  identity083Json,
  identity084Json,
  identity085Json,
  identity086Json,
  identity087Json,
  identity088Json,
  identity089Json,
  identity090Json,
  identity091Json,
  identity092Json,
  identity093Json,
  identity094Json,
  identity095Json,
  identity096Json,
  identity097Json,
  identity098Json,
  identity099Json,
  identity100Json,
  identity101Json,
  identity102Json,
  identity103Json,
  identity104Json,
  identity105Json,
  identity106Json,
  identity107Json,
  identity108Json,
  identity109Json,
  identity110Json,
  identity111Json,
  identity112Json,
  identity113Json,
  identity114Json,
  identity115Json,
  identity116Json,
  identity117Json,
  identity118Json,
  identity119Json,
  identity120Json,
  identity121Json,
  identity122Json,
  identity123Json,
  identity124Json,
  identity125Json,
] as const;
