import { readFile, readdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

import {
  ContentRegistrySchema,
  MedicationIdentityDefinitionSchema,
  type ContentRegistry,
  type MedicationIdentityDefinition,
} from '@psychsim/schemas';

export const DEFAULT_MEDICATION_IDENTITY_DIRECTORY = resolve(
  'content/catalogs/medications/identities',
);
export const DEFAULT_MEDICATION_IDENTITY_INDEX_PATH = resolve(
  'packages/content-runtime/src/medication-identities.generated.ts',
);
export const DEFAULT_CONTENT_REGISTRY_PATH = resolve('content/registry.json');

export interface MedicationIdentityIndexSyncOptions {
  identityDirectory?: string;
  indexPath?: string;
  registryPath?: string;
  write?: boolean;
}

export interface MedicationIdentityIndexSyncResult {
  identityCount: number;
  identityIds: string[];
  indexChanged: boolean;
  registryChanged: boolean;
  registryContentVersion: string;
}

const incrementPatchVersion = (version: string): string => {
  const match = version.match(/^(\d+)\.(\d+)\.(\d+)$/);
  if (!match) throw new Error(`Cannot increment non-semantic content version ${version}.`);
  return `${match[1]}.${match[2]}.${Number(match[3]) + 1}`;
};

export const renderMedicationIdentityIndex = (fileNames: readonly string[]): string => {
  const imports = fileNames.map(
    (fileName, index) =>
      `import identity${String(index + 1).padStart(3, '0')}Json from '../../../content/catalogs/medications/identities/${fileName}';`,
  );
  const values = fileNames.map(
    (_fileName, index) => `  identity${String(index + 1).padStart(3, '0')}Json,`,
  );
  return [
    '// Generated by tools/content-cli/src/sync-medication-identity-index.ts.',
    '// Do not hand-edit; identity files remain the canonical per-medication owners.',
    '',
    ...imports,
    '',
    'export const rawMedicationIdentityJson = [',
    ...values,
    '] as const;',
    '',
  ].join('\n');
};

export const synchronizeMedicationIdentityRegistry = (
  registry: ContentRegistry,
  identities: readonly MedicationIdentityDefinition[],
): {
  registry: ContentRegistry;
  changed: boolean;
} => {
  const next = structuredClone(registry);
  const entry = next.entries.find((candidate) => candidate.kind === 'medication_identity_catalog');
  if (!entry) throw new Error('Missing medication_identity_catalog registry entry.');
  const identityIds = identities
    .map((identity) => identity.id)
    .sort((left, right) => left.localeCompare(right));
  const currentIds = [...entry.categoryIds].sort((left, right) => left.localeCompare(right));
  if (JSON.stringify(currentIds) === JSON.stringify(identityIds)) {
    return { registry: next, changed: false };
  }
  entry.categoryIds = identityIds;
  next.contentVersion = incrementPatchVersion(next.contentVersion);
  return {
    registry: ContentRegistrySchema.parse(next),
    changed: true,
  };
};

export const syncMedicationIdentityIndex = async (
  options: MedicationIdentityIndexSyncOptions = {},
): Promise<MedicationIdentityIndexSyncResult> => {
  const identityDirectory = resolve(
    options.identityDirectory ?? DEFAULT_MEDICATION_IDENTITY_DIRECTORY,
  );
  const indexPath = resolve(options.indexPath ?? DEFAULT_MEDICATION_IDENTITY_INDEX_PATH);
  const registryPath = resolve(options.registryPath ?? DEFAULT_CONTENT_REGISTRY_PATH);
  const fileNames = (await readdir(identityDirectory))
    .filter((fileName) => fileName.endsWith('.identity.json'))
    .sort((left, right) => left.localeCompare(right));
  const identities = await Promise.all(
    fileNames.map(async (fileName) =>
      MedicationIdentityDefinitionSchema.parse(
        JSON.parse(await readFile(resolve(identityDirectory, fileName), 'utf8')) as unknown,
      ),
    ),
  );
  const expectedFileNames = identities.map(
    (identity) => `${identity.id.replace(/^medication\./, '')}.identity.json`,
  );
  if (JSON.stringify(expectedFileNames) !== JSON.stringify(fileNames)) {
    throw new Error('Medication identity filenames must exactly match their stable IDs.');
  }
  if (new Set(identities.map((identity) => identity.id)).size !== identities.length) {
    throw new Error('Medication identity files contain duplicate stable IDs.');
  }

  const renderedIndex = renderMedicationIdentityIndex(fileNames);
  const currentIndex = await readFile(indexPath, 'utf8').catch((error: unknown) => {
    if (
      error instanceof Error &&
      'code' in error &&
      (error as NodeJS.ErrnoException).code === 'ENOENT'
    ) {
      return null;
    }
    throw error;
  });
  const indexChanged = currentIndex !== renderedIndex;
  const registry = ContentRegistrySchema.parse(
    JSON.parse(await readFile(registryPath, 'utf8')) as unknown,
  );
  const synchronized = synchronizeMedicationIdentityRegistry(registry, identities);

  if (!options.write && (indexChanged || synchronized.changed)) {
    const changedOwners = [
      ...(indexChanged ? ['generated static import index'] : []),
      ...(synchronized.changed ? ['content registry membership'] : []),
    ];
    throw new Error(
      `Medication identity index drift: ${changedOwners.join(
        ' and ',
      )}. Run pnpm content:medications:index -- --write.`,
    );
  }
  if (options.write) {
    if (indexChanged) await writeFile(indexPath, renderedIndex, 'utf8');
    if (synchronized.changed) {
      await writeFile(registryPath, `${JSON.stringify(synchronized.registry, null, 2)}\n`, 'utf8');
    }
  }

  return {
    identityCount: identities.length,
    identityIds: identities.map((identity) => identity.id),
    indexChanged,
    registryChanged: synchronized.changed,
    registryContentVersion: synchronized.registry.contentVersion,
  };
};

export const runMedicationIdentityIndexCli = async (args: readonly string[]): Promise<void> => {
  const normalizedArgs = args.filter((argument) => argument !== '--');
  let write = false;
  for (const argument of normalizedArgs) {
    if (argument === '--write') {
      write = true;
      continue;
    }
    throw new Error(`Unknown medication-identity-index argument: ${argument}`);
  }
  const result = await syncMedicationIdentityIndex({ write });
  console.log(
    `PASS medication identity static index: ${result.identityCount} identities; registry ${result.registryContentVersion}; ${
      write ? 'synchronized' : 'no drift'
    }.`,
  );
};

const invokedPath = process.argv[1] ? pathToFileURL(process.argv[1]).href : null;
if (invokedPath === import.meta.url) {
  await runMedicationIdentityIndexCli(process.argv.slice(2));
}
